# Generated by Django 6.1 on 2026-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.URLField(blank=True, help_text='Google Drive link or direct image URL', max_length=2048)),
                ('text', models.TextField()),
                ('link', models.URLField(blank=True, max_length=2048)),
                ('start_date', models.CharField(blank=True, help_text='DD/MM/YYYY or empty', max_length=32)),
                ('finish_date', models.CharField(blank=True, help_text="DD/MM/YYYY, empty or 'unlimited'", max_length=32)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PremiumUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, help_text='Telegram user ID', unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Premium user',
                'verbose_name_plural': 'Premium users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(db_index=True)),
                ('day', models.IntegerField(db_index=True)),
                ('order', models.IntegerField(default=0)),
                ('year', models.IntegerField(blank=True, default=0)),
                ('emoji', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('source', models.URLField(blank=True, max_length=2048)),
            ],
            options={
                'ordering': ['month', 'day', 'order'],
                'unique_together': {('month', 'day', 'order', 'year', 'text')},
            },
        ),
    ]
