# Generated by Django 6.1 on 2026-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_requires_premium', models.BooleanField(default=True, help_text="If enabled, only premium users and admins see 'Week in history'. If disabled, visible to everyone.", verbose_name='Week in history — premium only')),
                ('month_requires_premium', models.BooleanField(default=True, help_text="If enabled, only premium users and admins see 'Month in history'. If disabled, visible to everyone.", verbose_name='Month in history — premium only')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot settings',
                'verbose_name_plural': 'Bot settings',
            },
        ),
    ]
