# Generated by Django 6.1 on 2026-08-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Uploaded image or copy from Google Drive — served from VPS. Preferred over URL.', null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='logo',
            field=models.URLField(blank=True, help_text='Google Drive link or direct image URL (source)', max_length=2048),
        ),
    ]
