# Generated by Django 6.1 on 2026-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_advertisement_logo_image_alter_advertisement_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='premium_button_suffix',
            field=models.CharField(blank=True, default='преміум доступ', help_text='Text in parentheses added to locked buttons, e.g. «преміум доступ». Edit here to translate to other languages.', max_length=64, verbose_name='Premium button suffix'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='premium_lock_mode',
            field=models.CharField(choices=[('inactive', 'Visible but inactive (shows «преміум доступ» suffix)'), ('hidden', 'Hidden for non-premium')], default='inactive', help_text='How premium-only buttons look for non-premium users.', max_length=16, verbose_name='Premium lock mode'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='month_requires_premium',
            field=models.BooleanField(default=True, help_text="If enabled, only premium users and admins can open 'Month in history'.", verbose_name='Month in history — premium only'),
        ),
        migrations.AlterField(
            model_name='botsettings',
            name='week_requires_premium',
            field=models.BooleanField(default=True, help_text="If enabled, only premium users and admins can open 'Week in history'.", verbose_name='Week in history — premium only'),
        ),
    ]
