# Generated by Django 6.1 on 2026-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_botsettings_premium_button_suffix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPublishSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master switch for daily auto publishing to the channel.', verbose_name='Auto publish enabled')),
                ('publish_time', models.TimeField(default='09:00', help_text='Daily check time (server/UTC time).', verbose_name='Publish time (UTC)')),
                ('days_of_week', models.CharField(default='0,1,2,3,4,5,6', help_text="Comma-separated weekday numbers: 0=Пн … 6=Нд, e.g. '0,2,4'", max_length=20, verbose_name='Days of week')),
                ('channel', models.CharField(default='@InsiderKidsNews', help_text='Channel username (@name) or numeric chat id. Bot must be admin with post rights.', max_length=64, verbose_name='Telegram channel')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto publish settings',
                'verbose_name_plural': 'Auto publish settings',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text="If enabled and today's day/week matches, bot will publish this event day to the channel at the scheduled time.", verbose_name='Auto publish'),
        ),
    ]
