# Generated by Django 6.1.1 on 2026-09-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_autopublishsettings_event_auto_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text_en',
            field=models.TextField(blank=True, default='', help_text='English translation of the text (via Gemma LLM or manual).', verbose_name='Text (English)'),
        ),
    ]
