# Generated by Django 6.1.1 on 2026-09-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_text_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('lang', models.CharField(choices=[('uk', 'uk'), ('en', 'en')], default='uk', max_length=2)),
            ],
            options={
                'verbose_name': 'User language',
                'verbose_name_plural': 'User languages',
            },
        ),
    ]
